{"name": "test_not_equal2", "status": "skipped", "statusDetails": {"message": "XFAIL reason: \n\n_pytest.outcomes.XFailed", "trace": "self = <TestCaseFunction test_not_equal2>, testcase = <LagouTest.tests.itesting_test.ITestingTest testMethod=test_not_equal2>\nrawexcinfo = (<class 'AssertionError'>, AssertionError('1 == 1'), <traceback object at 0x00000299077D7440>), reason = ''\n\n    def addExpectedFailure(\n        self,\n        testcase: \"unittest.TestCase\",\n        rawexcinfo: \"_SysExcInfoType\",\n        reason: str = \"\",\n    ) -> None:\n        try:\n>           xfail(str(reason))\nE           _pytest.outcomes.XFailed\n\nf:\\python39\\lib\\site-packages\\_pytest\\unittest.py:271: XFailed"}, "attachments": [{"name": "stdout", "source": "4453ca6f-b3b2-4a76-bf2a-eb447bf0d34e-attachment.txt", "type": "text/plain"}], "start": 1637482571398, "stop": 1637482571399, "uuid": "c809d737-f755-4f2d-9f6f-f697d6ceea92", "historyId": "3d30db8c579738b0923dc663408aa519", "testCaseId": "fe76d321e827bbaeaa67176c7ba86bda", "fullName": "main.ITestingTest#test_not_equal2", "labels": [{"name": "suite", "value": "main"}, {"name": "subSuite", "value": "ITestingTest"}, {"name": "host", "value": "TSJ-006171"}, {"name": "thread", "value": "33352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}